database:
  host: "124.221.246.5"
  port: "3306"
  user: "root"
  password: ""
  database: "lucky"
  params: "charset=utf8&parseTime=True&loc=Local"
email:
  host: "smtp.qq.com"
  port: 465
  sender: "2105753640@qq.com"
  secretKey: "ylodbtpycxylcbgd"
token:
  issuer: "lucky"

