database:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "root"
  database: "lucky"
  params: "charset=utf8&parseTime=True&loc=Local"
email:
  host: "smtp.qq.com"
  port: 465
  sender: "0@qq.com"
  secretKey: ""
token:
  issuer: "lucky"

